# Generated by Django 4.1.4 on 2023-04-02 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_users_city_users_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50, verbose_name='Ваш e-mail адрекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
